### ISSUE TITLE
Add support for alt input

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#101]
If we have time, this would be nice to include in the 1.1 release. See #98.

**Comment by terracoda** [comment]
Oh, that circle looks a lot like John's arm in John Travoltage, but in this case it has to go the full circle, and keep going in concentric circles.

And in the bottom accordion box the red dot leaves the screen.

Interesting for sure. Hopefully, not challenging.

**Comment by jessegreenberg** [comment]
While discussing with @amanda-phet and @kathy-phet, we noted that the keyboard input would control the angle. Up and right arrow would increase the angle, down and left arrow would decrease the angle.

**Comment by jessegreenberg** [comment]
@amanda-phet is going to draft a PDOM order, and also other descriptions in the "Tier 1" feature set (screen summaries).

For the "Voicing Tier 1" feature set, there is common code work to do to support this, but we will investigate what is needed. We may have time to include it.

**Comment by amanda-phet** [comment]
I might want to collaborate with @terracoda on this, but here is my first stab for the order: 

Dot on unit circle
Degrees/Radians radio button group 
Cos/Sin/Tan radio button group
Special Angles checkbox
Labels checkbox
Grid checkbox
Dot on graph
Reset all

**Comment by kathy-phet** [comment]
@amanda-phet, here is a variant to consider when taking into account Play and Control area split, and accordian boxes interactions: 

Play Area: 
Values Accordion button (in description, this orients to current state of the sim, value and angle)
Degree / Radians 
Dot on unit circle
Graph accordion button
Dot on the graph 
Cos/Sin/Tan radio button group

Control Area: 
Special Angles checkbox
Labels checkbox
Grid checkbox
Reset Button
Preference Menu
Keyboard Help

**Comment by jessegreenberg** [comment]
The alt input portion is ready for review and any other changes. I will make a new issue for other tier 1 description features.

- To start, I added the traversal order/categorization in https://github.com/phetsims/trig-tour/issues/101#issuecomment-2515854204.
- The unit circle and graph should behave the same with alt input. It behaves like this:
```ts
    moveOnHoldInterval: 75,
    dragDelta: Math.PI / 10,
    shiftDragDelta: Math.PI / 20
```
  - However, if special angles are visible, all key presses just move to the next special angle.
  - `moveOnHoldInterval` is the rate in ms for how fast new angles are set when you press and hold a key.

Some questions:
  - Does the focus highlight for the graph view line need to be customized? Especially when it goes to infinity?
  - Should the focus highlight on the unit circle pin be customized?
  - The drag listener is using a mode where the angle changes by a discrete amount. This makes it easy to reproduce specific angles. But there is another mode where the motion is more fluid (like in BASE/my-solar-system). Let me know if it should use this mode.
  - Do the drag deltas for keyboard input need to be adjusted?

**Comment by amanda-phet** [comment]
> Is it OK that the graph line (and its focus highlight) can be moved way off screen? That isn't ideal for accessibility, but it is an issue for mouse input too so I am not sure if we should do anything.

We'd like to add messaging if the point goes off screen, similar to this. "Point off scale!" would work. 
![image](https://github.com/user-attachments/assets/e0727170-c972-47d6-b0c2-211aab7163c5)

Decided to allow users to focus on this element even if it's off screen. 

>Does the focus highlight for the graph view line need to be customized? Especially when it goes to infinity?

We'd like to customize this to match the current pointer area, especially in the infinity case, and not allow this to be touched/clicked anywhere outside the white graph accordion box. 
![image](https://github.com/user-attachments/assets/77da2b03-3f5c-46a7-b371-d827324d1cec)


>Should the focus highlight on the unit circle pin be customized?

We like the idea of dilating this. We will also try a circle, but if it looks too much like a bullseye go back to a square. 

>The drag listener is using a mode where the angle changes by a discrete amount. This makes it easy to reproduce specific angles. But there is another mode where the motion is more fluid (like in BASE/my-solar-system). Let me know if it should use this mode.

We will stick with discrete steps so users can access any angles. 

>Do the drag deltas for keyboard input need to be adjusted?

For a discrete step we like 5º, and the shift modifier could be 0.5º.

**Comment by jessegreenberg** [comment]
Regarding the 'off-scale' icon, on slack @kathy-phet said. I see above @amanda-phet noted that too in the example.
> For Trig Tour the string would be "Point off scale!", since there is only one.

**Comment by jessegreenberg** [comment]
I believe everything described in https://github.com/phetsims/trig-tour/issues/101#issuecomment-2521534258 was done in the above commits. @amanda-phet can you please verify?

**Comment by amanda-phet** [comment]
Can we make the "Point off scale" text actually change to "Point off screen!" When discussing with @terracoda , the idea of a "scale" didn't make as much sense in this sim as it does in the number line sims. 

Also, if the accordion box is collapsed, can we make that "Point off screen" indicator not show up? It was a weird experience for me to have the graph collapsed and get that notification.

**Comment by jessegreenberg** [comment]
Great, done in the above commit.

**Comment by jessegreenberg** [comment]
> Also, if the accordion box is collapsed,

OK, got that too. Good point! Back to @amanda-phet.

**Comment by amanda-phet** [comment]
This is working great! There was one i18n issue but I mentioned it in https://github.com/phetsims/trig-tour/issues/100, so I think this can be closed!

**Comment by jessegreenberg** [comment]
Thanks bot - was just a TODO to finalize the traverasal order. Since this issue was revied, closing.
