### ISSUE TITLE
Add UI sound

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#105]
We decided this will be included as part of #98.

**Comment by jessegreenberg** [comment]
Sound has been enabled. It seems to be working for common code UI components, and the draggables are getting default sound too because of #103. I think that is all there is for this, can you please review @amanda-phet?

**Comment by amanda-phet** [comment]
Everything is working as expected. 

One thing I'm curious about is if the draggable points could have more of a "slider" sound, where you can get feedback that you are continuing to drag those. If that sounds like a bad idea, we can keep these as they are!

**Comment by jessegreenberg** [comment]
I see what you mean - there isn't an option for that in the "sound" drag listeners, but I suspect we could use that sound generator in this sim. Or maybe it should be added as an option to the common code listeners?

**Comment by amanda-phet** [comment]
@jessegreenberg will ask to collaborate with @jbphet about how to add a sound to this action (perhaps a similar click sound that sliders have).

**Comment by jessegreenberg** [comment]
Drag sounds like sliders were added, @amanda-phet can you please review? Should we actually remove the grab/release sounds now or leave those in? If this is what you had in mind, Ill review what I did with @jbphet.

I added a query parameter ?maxRotations to it is easier to find the limits. It must be an even value because of assumptions made in the old drag listener code. `?maxRotations=6`.

**Comment by amanda-phet** [comment]
I think this is working really well now!

**Comment by jessegreenberg** [comment]
OK, thanks. Using `ValueChangeSoundPlayer` was quite simple so I think it is OK to close without further review.
