### ISSUE TITLE
Possible to drag unit circle pin beyond max angle

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#109]
If you move your mouse quikcly while dragging the pin, it can go way beyond the maximum angle limit and then get stuck. Found while working on #105.

**Comment by jessegreenberg** [comment]
I think fixing this will help with #105. It is possible to drag the angle outside of the range and so sometimes we miss the boundary sound.

**Comment by jessegreenberg** [comment]
This was fixed in a commit for #105.

@amanda-phet are you OK with this behavior? It is now impossible to drag beyond the max angles, is that OK? In production you can drag a bit further like this:
![image](https://github.com/user-attachments/assets/faa070f4-e476-489e-b076-4e4c78024b59)

But if try hard you can almost go a full Pi/2 further than that.

As I mentioned in #105,
> I added a query parameter ?maxRotations to it is easier to find the limits. It must be an even value because of assumptions made in the old drag listener code. ?maxRotations=6.

**Comment by amanda-phet** [comment]
I'm not sure why it ever went that far, and the behavior right now on phettest looks great to me.
