### ISSUE TITLE
Asymptote lines are undraggable

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/trig-tour#11]
Test device: iPad 2 

Operating System: iOS 8.3

Browser: Safari

Problem description: When dragging the cursor continuously along the graph this issue is not present, but once the cursor is let go at an asymptote I cannot drag on the graph again. I have to drag on the unit circle then go back down to the graph.

Steps to reproduce: Select special angles. Drag cursor on graph to an asymptote. Release cursor. Attempt to drag the dotted line.

Severity:

Screenshots: 

Troubleshooting information (do not edit):
Name: ‪Trig Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/trig-lab/1.0.0-dev.14/trig-lab_en.html
Version: 1.0.0-dev.14 2015-07-23 21:40:49 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-115.5)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"579f8c66","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"3c45cb6f","branch":"phet"},"chipper":{"sha":"b737909c","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"35a12c18","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"24a4d9ab","branch":"master"},"scenery-phet":{"sha":"f3f30545","branch":"master"},"sherpa":{"sha":"b1ce7789","branch":"master"},"sun":{"sha":"dc08e5f3","branch":"master"},"trig-lab":{"sha":"f6cb7179","branch":"master"}}

**Comment by amanda-phet** [comment]
I noticed in today's interview a student trying to drag this line multiple times. I'll bring this up in the next design meeting.

**Comment by jessegreenberg** [comment]
The asymptote is draggable.  The arrow indicator also extends ArrowNode so its whole shape is also draggable.  Closing/
