### ISSUE TITLE
Reorder contents of Values accordion box

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/trig-tour#111]
As part of the tier 1 description design work, @kathy-phet and I realized that the angle measure is the first piece of information someone would probably want to know, then the coordinates, and then the trig value. 

We are hoping it would be an easy change to reorder the three values in the values accordion box so that the angle is first, then (x,y), then the trig value.

**Comment by jessegreenberg** [comment]
Sounds good, @amanda-phet can you please review main?

**Comment by amanda-phet** [comment]
Looks great! Thank you!
