### ISSUE TITLE
Capitalize units

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/trig-tour#112]
<img width="128" alt="image" src="https://github.com/user-attachments/assets/7f67b94a-f687-460b-aca8-69074965704e" />

I think we're trying to consistently capitalize things in sims, and these don't need to be lower case, so let's go ahead and capitalize them.

**Comment by jessegreenberg** [comment]
OK, I capitalized the labels on these radio buttons. I only changed the English strings, I don't know how to (or if we should) change any translations.

**Comment by amanda-phet** [comment]
I think it's fine to leave translations as they are. Thank you!
