### ISSUE TITLE
Use AccordionBox for GraphView

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#113]
GraphView uses an ExpandCollapseButton with a custom solution to look like an AccordionBox. It has this comment:

> The graph exists in a panel that can be minimized so that the graph is hidden on the display.  Since the
panel needs to shrink down to the size of the title when minimized, AccordionBox could not be used.

ACcordionBox now has this option, so maybe it can be used now:

```ts
  // If true, the expanded box will use the bounds of the content node when collapsed
  useExpandedBoundsWhenCollapsed?: boolean;
```

**Comment by pixelzoom** [comment]
Thanks for creating this issue @jessegreenberg - you saved me some work.  This is related to https://github.com/phetsims/sun/issues/919#issuecomment-2546357326.

**Comment by jessegreenberg** [comment]
This took longer than I hoped and ended up being a pretty significant redo of the graph. It was tricky because some graph components extend outside of the AccordionBox. So those Nodes had to be moved outside of the AccordionBox content in the scene graph. But it is done. The result looks a bit nicer than the published version too.

Closing.
