### ISSUE TITLE
odd history of version numbering

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/trig-tour#12]
I stumbled across this, mentioning both @dubson and @jbphet so that they are aware of this.

There are no dev versions of this sim published on spot.  Yet package.json shows `"version": "1.0.0-dev.16"`, as does dependencies.json.  And git history (see below) shows that "version" has been jumping all over the place. 

Is there some confusion about the purpose of version numbering and the convention that PhET is using?

![screenshot_571](https://cloud.githubusercontent.com/assets/3046552/9212999/36fddb0a-404b-11e5-88d0-c288cae06520.png)

Is there some confusion about the purpose of version numbering and the convention that PhET is using?

**Comment by pixelzoom** [comment]
Ah, I see a commit that says "Changing name of sim to Trig Tour".  Was this repository renamed from something else, perhaps trig-lab?  If so, that's something that the entire dev team needs to be notified about.

**Comment by dubson** [comment]
Correct!  The sim that was called trig-lab has been renamed trig-tour.  My bad for not announcing this with a github issue.  Will create issue now.

**Comment by ariel-phet** [comment]
@pixelzoom any further action required here, or can this be closed now?
