### ISSUE TITLE
Console statements at sim launch

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#15]
Found during code review, issue #14.  Two console statements are logged when the sim starts up which should probably be removed.

On TrigTourScreen line 31, and GraphView line 507:

![consolestatements](https://cloud.githubusercontent.com/assets/6396244/9308549/fcbc49c4-44c1-11e5-9b8c-1e84245977da.PNG)

For the error statement, it looks like this.trigFunction is initialized with an empty string so we reach the error statement the first time setIndicatorLine is called.  I also recommend replacing console.log with an assertion or console.error.

**Comment by dubson** [comment]
Issue resolved.  No console statements on start-up. GraphView.trigFunction was improperly initialized.
