### ISSUE TITLE
Sim does not handle i18n gracefully

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#16]
Noticed during #14.  There are a few internationalization issues, shown below.

For stringTest=double some panels start to overlap and go out of dev bounds.
![stringtest double](https://cloud.githubusercontent.com/assets/6396244/9308974/2b9622b8-44c4-11e5-803a-6c1a61164ce7.PNG)

for stringTest=someVeryLargeString... the panels can take up the whole screen.
![stringtest someverylargestring](https://cloud.githubusercontent.com/assets/6396244/9308995/4acf862e-44c4-11e5-8512-7893d73b26a6.PNG)

**Comment by dubson** [comment]
Hmmm.. seems to me that "stringTest = double" test is passed (though barely). Panels are still clearly visible and usable. Nothing is obscured.  Don't know how to improve this, except by writing code to change to smaller font when string is too long.  Don't know how to address the incredibly-long-string-test, seems to me to be  a Kabiyashi Maru test, and I don't recall that it was listed in the phet-info code review protocol.

**Comment by jessegreenberg** [comment]
My biggest concern with stringTest=double is that the control panel occludes the 'x' on the horizontal axis and it extends out of sim bounds (shown with the red bounding rectangle).  There is also no negative space between the unit circle and the control panel, which is bad for the sim "Feng Shui" :)

We started to test with strings larger than stringTest=double because we found that some translated strings could be larger than "double".  A string like "GO", for instance, could be much larger than "GO:GO" in a translated sim. Granted, the string test above is a Kabiuashi Maru test, but this has been a way to make sure that the sim can handle the largest strings possible.

Node now has a "maxWidth" option so it is pretty easy to make text translatable. For example:
```
    var yAxisLabel = new Text( potentialEnergyString, {
      rotation: -Math.PI / 2,
      font: HookesLawConstants.BAR_GRAPH_AXIS_FONT,
      right: yAxisNode.left - 1,
      centerY: yAxisNode.centerY,
      maxWidth: 0.85 * yAxisNode.height // constrain for i18n
    } );
```
Node has great documentation on maxWidth and how it scales down the node.

**Comment by jessegreenberg** [comment]
> seems to me to be a Kabiyashi Maru test...

Right you are, especially for string patterns with units or functional forms.  The recent consensus is that we make sure that ```stringTest=double``` passes cleanly and only use ```stringTest=someCrazyLongStringThatWouldLikelyBreakSomething``` as a a diagnostic tool for isolating problematic strings.

This sim no longer has any issues with ```stringTest=double```:

![string_test_double-fixed](https://cloud.githubusercontent.com/assets/6396244/10356721/4b3092de-6d37-11e5-9a93-0c9b6b972208.PNG)

**Comment by jessegreenberg** [comment]
I just noticed that the exception is ```theta``` along the x axis of the graph.  
![theta_cut_off](https://cloud.githubusercontent.com/assets/6396244/10356761/be6f8886-6d37-11e5-8671-e272b7554d88.PNG)

If ```theta``` is any longer than one character, it will get cut off at the end of the panel.  

One way to 'fix' this is to remove ```theta``` from the translatable strings.  The only reason I suggest this is that ```x``` and ```y``` along the axes of the unit circle are not translatable.  @amanda-phet and @dubson, is there a reason that ```x``` and ```y``` are not translatable but ```theta``` is?

Another potential way to fix this is to change the layout of the graph slightly to allow for more room for theta.

@amanda-phet do you have a preference?

**Comment by amanda-phet** [comment]
I don't know why theta is translatable. Perhaps other locales don't use that greek letter for angles? @dubson should comment.

**Comment by jessegreenberg** [comment]
Sounds good, thanks.  Will check in with him, reassigning to me.

**Comment by jessegreenberg** [comment]
> Perhaps other locales don't use that greek letter for angles

That seems likely, but for that reason ```x``` and ```y``` should be translatable as well.

**Comment by amanda-phet** [comment]
My intuition is that we should not make theta translatable. I tried to look it up and it seems like a variety of greek characters are appropriate for naming an angle, so no one should be confused by it. 

Also, I agree with you that the variables should all be consistently translatable.

**Comment by ariel-phet** [comment]
@amanda-phet I disagree. We should allow theta to be translatable, it does no harm to allow translators that freedom does it?

**Comment by amanda-phet** [comment]
I think the reason this issue was created because the "harm" could be if it is replaced with something longer than one character. Also, if we do allow theta to be translatable, shouldn't x and y also be?

**Comment by jessegreenberg** [comment]
> I think the reason this issue was created because the "harm" could be if it is replaced with something longer than one character.

Exactly, current position of x axis label on the graph does not allow for labels longer than one character.  The x axis label could be re-positioned or the graph layout could change to support longer strings.

> Also, if we do allow theta to be translatable, shouldn't x and y also be?

That is my thought as well.  When I initially discussed this with @dubson, I was told that those labels were specifically left out of translatable strings, but I cannot remember why.  Tried to reach him this afternoon but he was unavailable, I will try again soon for his input.

**Comment by ariel-phet** [comment]
We give translators the freedom to do whatever they wish in general, we tend to leave it up to them to make these sort of judgement calls. And yes, x and y should be translatable IMO

**Comment by ariel-phet** [comment]
Usually the only things we don't allow to be translated are more on the legal side, such as our names in the credits or our copyright statement or such.

**Comment by jessegreenberg** [comment]
```X```, ```Y```, and ```THETA``` are now all translatable strings.

The current placement of theta on the graph does not leave much room for translation:
![translatable_theta](https://cloud.githubusercontent.com/assets/6396244/10383337/df409d1c-6dea-11e5-8186-5ffc1003e1f7.PNG)

After three characters, theta is already too small:
![small_theta_translation](https://cloud.githubusercontent.com/assets/6396244/10383384/59c1a16c-6deb-11e5-83a5-652389d84bc6.PNG)

We can leave as-is if we expect the translation to be a single character.  But I recommend moving theta to provide just a little more space for more than one character:
![theta_moved](https://cloud.githubusercontent.com/assets/6396244/10383437/142fa72e-6dec-11e5-81a1-9d3ea2e8a5a5.PNG)
![theta_moved_translation](https://cloud.githubusercontent.com/assets/6396244/10383443/22cb083c-6dec-11e5-9db9-11dd2f0b06a7.PNG).

@amanda-phet, what would you prefer?

**Comment by jessegreenberg** [comment]
x-axis ```THETA``` in comment above is last of i18n issues.  This can be closed once that is resolved.

**Comment by amanda-phet** [comment]
I apologize I didn't realize that you were waiting on me to close this. Theta should not be above the axis as you suggested; it needs to be to the right of the arrow. If someone translates it with a longer string then they will just have a small label. I think it is highly unlikely and the placement is actually fairly important.

**Comment by jessegreenberg** [comment]
Sounds good @amanda-phet. Theta label is centered with x-axis again and maxWidth is reduced accordingly.  Closing.
