### ISSUE TITLE
Unnecessary common directory for model and view files

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#20]
Noticed during code review, #14. 

It is unconventional for PhET model and view files to share a common directory.  The common directory usually holds elements for sims which are shared across multiple screens.

It looks like Util.js only has constants which are used in view files, so Util.js could be moved to trig-tour/view.

**Comment by dubson** [comment]
Agreed.  Util.js moved to view folder.

**Comment by jessegreenberg** [comment]
Closing since this was completed.
