### ISSUE TITLE
Unconventional 'end' documentation at end of code blocks

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#23]
I notice that the end of large code blocks, functions, and constructors are documented with comments such as 

```//end positionLabels()``` or
```//end constructor```

This is done consistently throughout trig-tour code, but is an unconventional documentation pattern for other PhET sims.  Unless we think this pattern should be adopted for all other phet sims, these documentations should be removed.

**Comment by dubson** [comment]
I find this useful, so I can see what the block of code is about, without having to scroll to the top of the block to see what the function name is.

**Comment by ariel-phet** [comment]
@dubson I understand you find this useful but since it does not follow normal conventions, please remove it. Perhaps discuss with the other developers how they deal with the issue you bring up.

**Comment by jessegreenberg** [comment]
I have deleted the 'end' documentation at the end of some code blocks.  Closing.
