### ISSUE TITLE
bad license entry for dizzyMammoth.png

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/trig-tour#31]
dizzyMammoth.png has a license.json entry that does not conform to PhET's licensing policies. 

```
% grunt
...
>> Error: Error: Loader plugin did not call the load callback in the build:
>> mipmap:
>>   mipmap!TRIG_TOUR/dizzyMammoth.png: Error: unacceptable license entry for TRIG_TOUR/dizzyMammoth.png

% 
```

**Comment by jessegreenberg** [comment]
This build error would be resolved by completing issue #19.

**Comment by pixelzoom** [comment]
This is still an issue as of 8/25/15, testing with test-server.

**Comment by pixelzoom** [comment]
license.json entry:

```
  "dizzyMammoth.png": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "",
    "license": "contact phethelp@colorado.edu",
    "notes": "stolen from Web"
  }
```

"stolen from the Web"? If it's check into GitHub (publicly visible) then it's a copyright violation.

**Comment by jessegreenberg** [comment]
license.json has been updated with the correct entry and image.  Copyright violation removed as dizzyMammoth is not being used in the sim.

trig-tour builds cleanly and passes licensing tests.  Closing.
