### ISSUE TITLE
Complete sim credits in main

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#56]
There is a TODO in trig-tour-main.js for sim credits.  
```
  var simOptions = {
    credits: {
      //TODO fill in proper credits, all of these fields are optional, see joist.AboutDialog
      leadDesign: 'Amanda McGarry and Michael Dubson',
      softwareDevelopment: 'Michael Dubson',
      team: 'Ariel Paul, Kathy Perkins',
      qualityAssurance: 'Steele Dalton'
      //graphicArts: '',
      //thanks: ''
    }
  };
```
Once the sim credits are completed, this TODO reminder can be deleted.

**Comment by jessegreenberg** [comment]
@amanda-phet, could you please verify that these credits are correct?

![trig-tour-credits](https://cloud.githubusercontent.com/assets/6396244/10490079/68775218-725c-11e5-8dd0-3d5f63ffd8ab.PNG)

**Comment by ariel-phet** [comment]
@jessegreenberg, you should put Michael Dubson first on lead design (alphabetically)

**Comment by ariel-phet** [comment]
Other than that, credits are correct

**Comment by jessegreenberg** [comment]
Done in commit above.  Great, closing the issue then.
