### ISSUE TITLE
Background for dizzyPhetGirl should be transparent

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#57]
The new PhET girl image looks great!  However, I notice that the image background is not transparent so it looks a little strange when it pops up.  It blocks much of the simulation and makes PhET girl look off center.  I am wondering if the dizzyPhetGirl image background should be transparent?

This is unrelated to code review, and is more of a design question.  If the look is as it is intended, feel free to close.  @amanda-phet do you have any thoughts on this?

![background_alpha](https://cloud.githubusercontent.com/assets/6396244/9592413/e4f57cfe-4fff-11e5-8b12-3670855c77b8.PNG)

**Comment by amanda-phet** [comment]
It is supposed to be transparent, and I gave @dubson the correct .png. Perhaps he hasn't updated it?

**Comment by amanda-phet** [comment]
It looks like the images folder has a .jpeg and a .png. The .jpeg should be deleted so that it is never used, and the .png should be used.

**Comment by jessegreenberg** [comment]
.jpeg has been deleted for the dizzyPhetGirl, and the .png is being used.  Image background is now transparent.  There is another issue open for adding the image asset, so this can be closed.
