### ISSUE TITLE
Drawing the spiral shape performs poorly on iPad2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#62]
While playing with the spiral to reproduce issue #61, I became concerned about the performance of the spiral on iPad2.  After ~5 rotations, the drag behavior bogs down as the number of line segments in the shape grows.

As the spiral shape changes, it is unfortunate to redraw the whole thing.  The shape itself only changes by a single line segment every time the angle changes. For spiral consisting of 1200 line segments, 1199 of them are being redrawn, but do not need to change.

@jonathanolson recommends two solutions that might perform better:

1) A clipping region that grows with the spiral, the full spiral always exists on the unit circle.
2) Maintaining individual 'circles' on the spiral so that only one circle needs to be redrawn as the angle changes.

I will first try option 1 above, it seems the simplest and perhaps the most beneficial to performance.

**Comment by jessegreenberg** [comment]
Commit 5ee1bb9de88055dc3dc45194319dbbf371a96c5b was an attempt at solution 1 above.  Performance is better, but not as improved as I was hoping.

Using ?profiler, FPS for dev.18 (before commit above) is about 7 for larger model angles.

FPS after applying option 1 is up to 14 fps at the extreme angles for iPad2.

**Comment by jessegreenberg** [comment]
No noticeable performance improvements on Windows 7 Chrome 46.

**Comment by jessegreenberg** [comment]
Commit above tried to override bounds computations for arrow nodes, no noticeable performance increase on iPad2.

**Comment by jessegreenberg** [comment]
Removing updates to the clipping shape shows no further performance improvement.  This makes me think that further pursuits to enhancing performance should be in elements that are not related to the spiral such as the ReadoutNode or the GraphView.

**Comment by jessegreenberg** [comment]
First commit above replaces the uses of SubSupTtext with the Unicode symbol for units in degrees to avoid recreating Text nodes.
Second commit removes a function closure that was being called with Underscore in addSegment to diminish the burden on garbage collection.

The fps on iPad2 is around 12-16 with the above changes.  Next steps will be to remove various panels of the screenView to isolate the expensive sections.

**Comment by jessegreenberg** [comment]
Removing various sections results in the following frame rates:

* Removing the GraphView entirely: 8-14 fps (11 average)
* Removing the ReadoutDisplay: 11-16 fps (11 average)
* Unlink spiral shape from model properties: 6-10 fps
* Removing TrigTourSpiralNode entirely: 16-21 fps (18 average)
* Removing TrigTourSpiralNode and ReadoutDisplay: 20 fps
* Removing TrigTourSpiralNode, GraphView, ReadoutDisplay: 30fps

Only after removing all three dynamic elements is a substantial performance benefit is observed.

**Comment by jessegreenberg** [comment]
In commit https://github.com/phetsims/trig-tour/commit/7bf96162a742eab7d83c00d737444d39e1f82893 above, the clip area shape is drawn with two arcs instead of line segments.

@jonathanolson suggested that performance could be enhanced by restructuring the FractionNode so the entire node is not reconstructed every update.  This is what I will look into next

@jonathanolson also suggests that many performance issues involve bounds and hit computations.  He is working on improving how scenery handles these now.  In the mean time, he pointed out cases where restructuring node parent/child relationships will avoid expensive collision computations, I will take a look at these as well.

**Comment by jessegreenberg** [comment]
Reviewing the code in ReadoutNode and FractionNode, it looks like the implementation is rewriting all nodes on the panel, not just those that are visible.  Performance could benefit from a restructure of the ReadoutNode.  The code would also benefit from a reduction in complexity.

**Comment by jessegreenberg** [comment]
Recalling that removing the entire ReadoutNode from the ScreenView has no significant impact on performance, I am inclined to wait until @jonathanolson completes the Scenery optimizations mentioned above to give the ReadoutNode an overhaul in implementation.

**Comment by jessegreenberg** [comment]
Preventing block fitting seems to have little impact on performance in trig-tour.  Frame rate fluctuates between 8-14 fps, about the same as before.

**Comment by jessegreenberg** [comment]
Met with @jonathanolson to discuss potential performance improvements.  He gave the following list of recommendations that could improve performance by reducing the number of hit, fit, resize, and bounds related computations.

  - [ ] Axis labels should not be children of the axes.
  - [ ] Arrow should not be a child of the draggable circle node
  - [ ] Set ```resize=false``` on Hboxes and VBoxes
  - [ ] Include ```preventFit``` flag on text that gets fit every frame
  - [ ] HTMLText should be replaced with Text with italic phetfont.
      - An image of the italic theta could also be  used
  - [ ] New implementations for the SpiralNode
     - [ ] Convert path to image
     - [ ] Opaque path in front of the spiral with a changing shape
     - [ ] Canvas optimization for drawing the spiral

**Comment by jessegreenberg** [comment]
For the remaining two recommendations, I tried removing the spiral Paths and replacing all HTMLText  with Text before starting.  Together, these optimizations improved performance by a significant amount.  Removing the spirals seemed to provide the most benefit, but replacing HTMLText also helped.  I will start with the HTMLText replacement because it is the easiest then move to optimizing the spiral.

**Comment by jessegreenberg** [comment]
HTMLText replaced with scenery Text.  Performance is better, but not quite there yet.  Up next is the SpiralNode.

**Comment by jessegreenberg** [comment]
TrigTourSpiralNode converted to image.  Performance is much improved!  However, the load time for the iPad2 is now over 40 seconds.  Perhaps with ```width``` and ```height``` variables of the ```toImage``` callback we can reduce the resolution?  If not, we can either:

1) Add other image files to assets that represent the spiral node
2) Try one of the other two solutions listed above
 >  Opaque path in front of the spiral with a changing shape
 Canvas optimization for drawing the spiral

If we can get the load time under control, the running performance seems acceptable now.

**Comment by jessegreenberg** [comment]
We should be able to save the the rendered image and then load back in.  Potentially as a mipmap to improve quality for certain browsers.  This would not be a difficult change.  Drawing code will be left in TrigTourSpiralNode for documentation.  This should enhance image quality and bring down the load time.

**Comment by jessegreenberg** [comment]
Unfortunately, the image doesn't scale perfectly when taken from chrome resource tools.  The arrow head of the spiral needs to follow the spiral path exactly, and it looks off if the image gets scaled incorrectly by chrome resources.

**Comment by jessegreenberg** [comment]
Improving image resolution does not help.

**Comment by jessegreenberg** [comment]
With some minor offsets, the spiral image is centered correctly.  Pulling in the images from chrome resources reduced load time to ~9 seconds on the iPad2 (RequireJS version).

**Comment by jessegreenberg** [comment]
I now notice an artifact from this optimization, only on iPad2:

![artifact](https://cloud.githubusercontent.com/assets/6396244/12524325/7dd09190-c119-11e5-9006-5c98da6172c9.png)

A very small piece from the next spiral rotation is visible.

**Comment by jessegreenberg** [comment]
Slight increase to the initial radius of the arc for the clip area does the trick.

**Comment by jonathanolson** [comment]
If you are using toImage() to generate it in the first place, it should provide in the callback an exact offset that you will need to position it properly.

**Comment by jessegreenberg** [comment]
True, but I want to avoid calling toImage() since it takes so long to render the image on iPad.  When toImage was used, it was centered correctly.  It looks like the saved image had a couple pixels of negative space around the bounds.  Accounting for this, the image is aligned correctly again.

**Comment by jessegreenberg** [comment]
Performance on the iPad is great.  Recent dev testing verified that performance on iPad2 is satisfactory with a good load time. This issue can be closed.
