### ISSUE TITLE
Testing FormulaNode in trig-tour

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#63]
As part of https://github.com/phetsims/scenery/issues/457, I am going to test FormulaNode by using it to display the equations in trig tour.

My plan is to recreate the equations so they look exactly the same as before.  However, since I am revisiting them, now would be a good time to change the equation style if desired.

@amanda-phet, do you have any changes in mind for the look and feel of the equations in trig-tour now that scenery has formula support?

**Comment by amanda-phet** [comment]
I would keep the sizes and layout the same, but I also expect things like the square root and π to change in appearance (in a good way). If you come across something specific let me know!

**Comment by jessegreenberg** [comment]
In phetsims/tasks#425, @amanda-phet said 

> If the square root is an issue that can't be fixed, we may want @jessegreenberg to pause on implementing this in Trig Tour (which uses square roots).

The issue was closed, but what is the status of this?  Do the square roots look poor enough to stop implementing/testing in trig-tour?

**Comment by jessegreenberg** [comment]
Assigned to @amanda-phet but @ariel-phet may want to determine if testing and review of FormulaNode should continue as well.

**Comment by ariel-phet** [comment]
@jessegreenberg probably worth continuing to review FormulaNode, but given the issues with the square root probably not worth implementing in trig-tour

**Comment by jessegreenberg** [comment]
OK, sounds good.  I will back out of changes in trig-tour but continue to review FormulaNode.  Closing this issue and picking back up in https://github.com/phetsims/scenery/issues/457.
