### ISSUE TITLE
'Angle' of ReadoutNode should use a string pattern for i18n

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#64]
While investigating #62, @jonathanolson pointed out that the angle value of ReadoutNode still does not support RTL units for i18n and should use a string pattern.

**Comment by jessegreenberg** [comment]
Here is the readout:
![readout](https://cloud.githubusercontent.com/assets/6396244/12059723/f0af2036-af1d-11e5-96ca-ddb7aedd9c17.PNG)


If we allow the order of the second row to be reversible, we should do the same for the first and third row.  I have a vague memory that @ariel-phet and @jessegreenberg discussed this already and verified that this was a case where RTL languages would read these equality statements LTR.

If my memory is correct, this issue can be closed.  Otherwise, please reassign to me and I can work on allowing the ordering to change for i18n.

**Comment by ariel-phet** [comment]
Correct @jessegreenberg - we have confirmed in several sims (like Graphing Lines) that it is fine to leave mathematical statements as purely LTR.
