### ISSUE TITLE
1.0.0-dev.19 proposed layout changes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/trig-tour#70]
@amanda-phet @dubson @ariel-phet @jessegreenberg I have a few layout questions with this sim. It's obvious to me that some panels are not aligned well (in my opinion) and some things look out of place. Look below, and if there was ever a reason that changes 1,2, and 3 shouldn't happen and they are the way they are for a reason, don't worry about it. I do think change 4 needs to happen regardless.

I made a mock up, it's not perfect (Microsoft Paint has its limitations). Original sim pictured second.

1. Moved the Values panel up and to the left to be horizontally aligned with the unit circle box and vertically aligned with the graph display.
2. Moved the radio/check-box panel up and to the right to be horizontally aligned with the unit circle box and vertically aligned with the graph display. (I might have moved it too high)
3. Moved the "X" variable inside the white rectangle and above the arrowhead.
4. Not pictured below, but the reset all button needs to be increased in size, it's much smaller than other sims (re-sizing it in Paint looked ugly so use your imagination!).

![trigtourmock](https://cloud.githubusercontent.com/assets/5863899/12564218/58d4ebbc-c36b-11e5-9926-ffd5689ba192.png)

![trigb4mock](https://cloud.githubusercontent.com/assets/5863899/12564720/00506892-c36e-11e5-8a26-eb1e45656cf0.PNG)

For phetsims/tasks/issues/486

**Comment by amanda-phet** [comment]
Thanks @phet-steele . 

1-2. I'm fine with that change. The background and stroke around the circle came later in the design and we just never adjusted things. 
3. I see where you're coming from but convention is to label to the right of the arrow. Instead I would vote for making that panel wider to fit the x (similar to the graph below). 
4. How strange! Let's definitely fix that!

**Comment by phet-steele** [comment]
@amanda-phet making the panel wider to fix the x is probably a better idea. I just realized my way would have ran into problems with the y when labels were turned on:

![trigxyprob](https://cloud.githubusercontent.com/assets/5863899/12564872/d75defee-c36e-11e5-9a68-7d87cd7cb46b.PNG)

**Comment by jessegreenberg** [comment]
Here is the proposed change list after comments from @phet-steele and  @amanda-phet.

- [ ] Move the Values panel up and to the left to be horizontally aligned with the unit circle box and vertically aligned with the graph display.
- [ ] Move the radio/check-box panel up and to the right to be horizontally aligned with the unit circle box and vertically aligned with the graph display.
- [ ] Make the unit circle panel wider to fit the x (similar to the graph below).
- [ ] ReseAllButton should be default size.

@ariel-phet @dubson any other comments before I start this?

**Comment by dubson** [comment]
I don't think I have any objection with re-alignment, definitely worth trying to see what it looks like.  As for ResetAllButton, I prefer a lighter, smaller button than the norm (but with the same size hit area).

**Comment by ariel-phet** [comment]
Those changes look fine to me.

**Comment by phet-steele** [comment]
@dubson wants to revise what he said above, I just spoke with him. He would prefer us to keep the button small but make the hit area larger (as large as the normal one I presume) because he realizes there is trouble hitting this button on a touch screen.

**Comment by jessegreenberg** [comment]
I made the above changes, keeping the size of the ResetAllButton and increasing the radius of the touch area. Here is the new layout.

![new-layout](https://cloud.githubusercontent.com/assets/6396244/12629660/0ffbd1ac-c506-11e5-89e7-f8bc272bcf57.PNG)


Reassigning to @amanda-phet for review, but tagging @dubson @phet-steele @ariel-phet  for any additional review comments.

**Comment by amanda-phet** [comment]
I appreciate the screenshot so I don't have to hunt down the dev version. 

Looks good to me! However I see one minor tweak that would be nice but is not essential:

The y-axis for the unit circle goes edge-to-edge within the containing panel. Can we do the same with the y-axis for the graph of the function?

**Comment by jessegreenberg** [comment]
Sure @amanda-phet!  Would you like to increase the height of the y-axis or decrease the height of the panel?

**Comment by amanda-phet** [comment]
Probably increase the height of the y-axis since the panel is already small.

Thanks!

**Comment by jessegreenberg** [comment]
Sounds good!  Here is what the change looks like:
![new-layout](https://cloud.githubusercontent.com/assets/6396244/12632774/bb0139b4-c517-11e5-8b75-9f1b6b86629a.PNG)

What do you think @amanda-phet?

**Comment by ariel-phet** [comment]
@jessegreenberg please do increase the size of the reset all button. I understand @dubson does not want it the default size, but we do also want consistency, and it is oddly small currently. It does not need to be the full default size, but perhaps split the difference between the current size and the default size.

**Comment by jessegreenberg** [comment]
I increased the radius of the button a bit so that it is between the default and the previous size.  Here is the what the layout looks like now:

![capture](https://cloud.githubusercontent.com/assets/6396244/12635909/6fe19e78-c545-11e5-80a8-eb41bedc7492.PNG)

Back to @amanda-phet.

**Comment by amanda-phet** [comment]
It all looks great to me.

**Comment by jessegreenberg** [comment]
Great, thanks! Closing.
