### ISSUE TITLE
Breaking the rotation limit

### ISSUE THREAD

**Issue by phet-steele** [phetsims/trig-tour#71]
@jessegreenberg you saw me do this already, but it's possible to move past the rotation limit and make the arrow unresponsive. To do this you simply need to rotate really fast, I'd recommend not rotating in a circular direction but instead move in a straight line from one side of the circle to the next to "skip" the arrow around (really that's the best anyone could explain this :smile:)

The head of the arrow detaches from the trace, too:

![trito](https://cloud.githubusercontent.com/assets/5863899/12564603/5761ad90-c36d-11e5-9d91-59ba25a36558.gif)

Tested on 1.0.0-dev.19 with Win 8.1 FF & Chrome, and iPad 2 iOS 9.3 beta. For phetsims/tasks/issues/486

**Comment by jessegreenberg** [comment]
Great catch @phet-steele, thanks!  This should be fixed, would you mind verifying that it can no longer be reproduced?

I also changed the drag handler slightly so that the sim will stay in `special angles` mode even if the rotor is dragged too far.

**Comment by jessegreenberg** [comment]
@phet-steele I have a new dev version out: http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.20/trig-tour_en.html

Would you be able to verify that this issue is resolved in that version?

**Comment by phet-steele** [comment]
@jessegreenberg verified!
