### ISSUE TITLE
Edge has some random lines in the Values panel

### ISSUE THREAD

**Issue by phet-steele** [phetsims/trig-tour#72]
No special steps required, here they are:

![trigtourlinesonedge](https://cloud.githubusercontent.com/assets/5863899/12588649/e30c3faa-c416-11e5-97e4-5e0472e18c33.JPG)

Tested on 1.0.0-dev.19 with Galileo (Win 10). For phetsims/tasks/issues/486

Troubleshooting information:
Name: ‪Trig Tour‬
URL: http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.19/trig-tour_en.html
Version: 1.0.0-dev.19 2016-01-22 23:12:47 UTC
Features missing: touch
Flags: pointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1536x710
Pixel Ratio: 1.25/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"5a39ec57","branch":"master"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"48ab5fab","branch":"master"},"chipper":{"sha":"57c99807","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"8b666baf","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"953fe860","branch":"master"},"scenery-phet":{"sha":"778e9c76","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"39a79196","branch":"master"},"tandem":{"sha":"5388a9e4","branch":"master"},"trig-tour":{"sha":"53c8d262","branch":"master"}}

**Comment by jessegreenberg** [comment]
Fixed by explicitly setting the stroke and the lineWidth.  Verified that they are no longer visible.  Closing.
