### ISSUE TITLE
Special angles rotation moves (x,y)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/trig-tour#73]
Rotating while in Special Angles view will move the (x,y) values upward on some devices. Rotation speed doesn't matter, fast rotating only speeds up the process. Reset all does not fix this, only refreshing the page will. Video in iE11 Win 8.1:

![trito2](https://cloud.githubusercontent.com/assets/5863899/12589647/0885f51e-c41c-11e5-8717-1b1c74a5f9ba.gif)

Multiple devices were tested and some showed this behaviour more quickly than others. Seen on (in order of prominence):
IE11 (Win 8.1, personal)
Safari (OSX 10.10.5, Curie)
Edge (Win 10..., Galileo)
FF (Win 8.1, personal)
Chrome (All above OSs)

Could not get it to happen on iPad 2 iOS 9.3 beta (Tycho), or its just very subtle.
For phetsims/tasks/issues/486

Troubleshooting information:
Name: ‪Trig Tour‬
URL: http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.19/trig-tour_en.html
Version: 1.0.0-dev.19 2016-01-22 23:12:47 UTC
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; GWX:DOWNLOADED; MALNJS; rv:11.0) like Gecko
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"5a39ec57","branch":"master"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"48ab5fab","branch":"master"},"chipper":{"sha":"57c99807","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"8b666baf","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"953fe860","branch":"master"},"scenery-phet":{"sha":"778e9c76","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"39a79196","branch":"master"},"tandem":{"sha":"5388a9e4","branch":"master"},"trig-tour":{"sha":"53c8d262","branch":"master"}}

**Comment by phet-steele** [comment]
On chromebook the (x,y) values move downward...

**Comment by jessegreenberg** [comment]
Reproduced on Windows 10 Chrome 48, but the effect is *much* less significant, it took ~60 rotations before I noticed.

**Comment by jessegreenberg** [comment]
This should be fixed.  I tested the commit above with Windows 10 and Chrome, Edge, and Firefox, as well as iPad2 Safari.  Unable to reproduce.

**Comment by jessegreenberg** [comment]
@phet-steele I have a new dev version here: http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.20/trig-tour_en.html

Would you be able to verify that this is fixed?

**Comment by phet-steele** [comment]
@jessegreenberg fixed!
