### ISSUE TITLE
Edge does not show asymptote

### ISSUE THREAD

**Issue by phet-steele** [phetsims/trig-tour#76]
@jessegreenberg instead Win 10, Edge shows a solid line (not dashed):

![trigtourasymptoteonedge](https://cloud.githubusercontent.com/assets/5863899/12792359/a786018e-ca68-11e5-8fe1-5e3404d5b449.JPG)

Tested with Galileo. For phetsims/tasks/issues/495

Troubleshooting information:
Name: ‪Trig Tour‬
URL: http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-rc.1/trig-tour_en.html
Version: 1.0.0-rc.1 2016-01-29 19:53:55 UTC
Features missing: touch
Flags: pointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1536x710
Pixel Ratio: 1.25/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"3729b0d8","branch":"HEAD"},"babel":{"sha":"5efa9108","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"HEAD"},"chipper":{"sha":"0e7f348d","branch":"HEAD"},"dot":{"sha":"ddf82014","branch":"HEAD"},"joist":{"sha":"4c228a32","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"phet-core":{"sha":"874a703d","branch":"HEAD"},"phetcommon":{"sha":"3db92af3","branch":"HEAD"},"scenery":{"sha":"d0753b38","branch":"HEAD"},"scenery-phet":{"sha":"2a28aee5","branch":"HEAD"},"sherpa":{"sha":"bf82eb95","branch":"HEAD"},"sun":{"sha":"163252c0","branch":"HEAD"},"tandem":{"sha":"5388a9e4","branch":"HEAD"},"trig-tour":{"sha":"1695686c","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
It looks like Edge handles lineDash differently than other browsers?  I observe this issue in Acid-Base Solutions as well.  However, I do not notice this in Capacitor Lab: Basics, or Area Builder, bother simulations that use lineDash in view code.

Creating an issue in scenery.

**Comment by jonathanolson** [comment]
As noted in the Scenery ticket, I fixed this bug with the commit https://github.com/phetsims/scenery/commit/838086baa1514417379c20f5d945ced6258d74c2.

**Comment by jessegreenberg** [comment]
Awesome, thank you @jonathanolson!  Looks great, verified as fixed on Edge.  Closing.
