### ISSUE TITLE
Teaching tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/trig-tour#78]
@phet-steele to help out @amanda-phet we were hoping you could start on the teacher tips for this sim. More details in an email.

**Comment by phet-steele** [comment]
I finished my draft and sent it to @amanda-phet yesterday (2/4) afternoon.

**Comment by amanda-phet** [comment]
Final docs are uploaded to the google drive folder. The PDF can be uploaded when the rest of the sim information is entered on the site.
