### ISSUE TITLE
Upload website info and make sim visible

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/trig-tour#79]
@phet-steele this should be your top priority for Monday 2/8/2016

Trig-tour has been published to the website but the project is not yet visible.

Before the sim is made visible we need to upload the related website info. @amanda-phet put all the necessary information into the [design doc](https://docs.google.com/document/d/12IGXWoa7LdWjlMFH1aVvkOZOL1cFkTOLc0mGRKWmy3Q/edit#heading=h.mv3glozfezqu) under the "website info" section

Once you have completed uploading this info, check off the relevant items in #1

**Comment by phet-steele** [comment]
@ariel-phet done!

**Comment by ariel-phet** [comment]
excellent closing
