### ISSUE TITLE
Reset button does not reopen drop "values" menu

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/trig-tour#8]
Tested on OSX 10.10.4 Safari 8.0.7 and Chrome 43
Minor Severity 
If you minimize the "Values" menu, then click the reset button, the "Values" menu does not return to its initial expanded position.

**Comment by elisemorgan** [comment]
Also seen on iPad2 iOS8.3

**Comment by amanda-phet** [comment]
This should definitely return to its original state.

**Comment by dubson** [comment]
It was a bug!  Bug fixed.
