### ISSUE TITLE
Replace PropertySet

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/trig-tour#84]
From https://github.com/phetsims/axon/issues/102, PropertySet is deprecated and should be replaced with  Property.

**Comment by veillette** [comment]
Assigning to @jessegreenberg  for review.

**Comment by jessegreenberg** [comment]
Changes look great, and thanks for the improvements to JSDoc and other documentation! Thanks so much for taking this one @veillette!

**Comment by jessegreenberg** [comment]
Ah, there might be an issue with the radio buttons for radians vs degrees, the values don't seem to update when those change.

**Comment by veillette** [comment]
setAngleReadout is AngleReadoutRow is not correct.

**Comment by jessegreenberg** [comment]
Indeed thanks, should be fixed in the above commit.

**Comment by veillette** [comment]
Good catch. 
I've played some more with the simulation, checking on and off the checkBoxes and radio buttons. It behaves as expected.   

fuzzMousing with assertions enabled did not  trigger anything..

**Comment by jessegreenberg** [comment]
Thanks @veillette, I think that is all for this issue then.
