### ISSUE TITLE
Font Size and Alignment of graph type is incorrect.

### ISSUE THREAD

**Issue by veillette** [phetsims/trig-tour#86]
![image](https://user-images.githubusercontent.com/7633344/27962065-bc624718-62fe-11e7-84b1-e38ecbe365db.png)

While working on #84 , I noticed the font size and alignment on the cosine in the panel is incorrect. In addition the fontsize of the y-axis does not match the published version.

![image](https://user-images.githubusercontent.com/7633344/27962194-1c900a30-62ff-11e7-8f35-0a2ebb8a04a8.png)

**Comment by veillette** [comment]
TrigFunctionLabelText is responsible for the layout of the two labels.

**Comment by veillette** [comment]
I'm a bit flummoxed since it looks very proper.
```
  // constants
  var DISPLAY_FONT = new PhetFont( { size: 20 } );
  var DISPLAY_FONT_ITALIC = new PhetFont( { size: 20, style: 'italic' } );

  // strings
  var thetaString = require( 'string!TRIG_TOUR/theta' );

  /**
   * Constructor.
   *
   * @param {string} trigFunctionString - label for the trig function
   * @param {Object} [options]
   * @constructor
   */
  function TrigFunctionLabelText( trigFunctionString, options ) {

    options = _.extend( {
      trigFunctionLabelFont: DISPLAY_FONT,
      thetaLabelFont: DISPLAY_FONT_ITALIC
    }, options );

    // build the text for the trig function label
    var trigTitleText = new Text( trigFunctionString, options.trigFunctionLabelFont );

    // create the text for the mathematical symbol theta
    var trigThetaText = new Text( thetaString, options.thetaLabelFont );

    // build the text, placing both function and theta labels in an HBox
    HBox.call( this, { children: [ trigTitleText, trigThetaText ], spacing: 0, resize: false } );

  }
````

**Comment by veillette** [comment]
For the record, this is present in Firefox, and it is present on the build version as well.

**Comment by veillette** [comment]
One issue is that the options are not passed properly.

````
  // build the text for the trig function label
    var trigTitleText = new Text( trigFunctionString, { font: options.trigFunctionLabelFont } );

    // create the text for the mathematical symbol theta
    var trigThetaText = new Text( thetaString, { font: options.thetaLabelFont } );
```

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/27964306-cc9616e4-6305-11e7-9586-bc561fb1e0c9.png)


Passing the options properly fixes the sizing and boldness but there is a misalignment issue.


I'm still very perplexed because the published version  shows none of these problems.

**Comment by veillette** [comment]
For the record, the published version shows

![image](https://user-images.githubusercontent.com/7633344/27964556-af9c7596-6306-11e7-9ceb-f9c7612279f8.png)

**Comment by veillette** [comment]
Assigning to @jessegreenberg since he has worked on TrigFunctionLabelText. 

Please reassigned to me once you have tackled this as I would like to commit my conversion from PropertySet to Property. I'm waiting on this because I would rather not conflate these two issues.

**Comment by jessegreenberg** [comment]
Thanks for catching @veillette, I am not sure why this has changed.  I will take a look at this today.

**Comment by jessegreenberg** [comment]
> One issue is that the options are not passed properly.
>I'm still very perplexed because the published version shows none of these problems.

Me too!!

**Comment by jessegreenberg** [comment]
Layout and font of the "=" signs in the bottom row are wrong too.

**Comment by veillette** [comment]
My best guess is that it must have to do with a change on how Scenery Text handles options.

**Comment by jessegreenberg** [comment]
For the "=" Text, I see again
```js
    var rightEqualText = new Text( equalString, DISPLAY_FONT_LARGE_BOLD );
```

I wonder if Text used to take font param as an alternative to options?

**Comment by jessegreenberg** [comment]
Font issues were sorted as part of phetsims/scenery#642, but the layout is still an issue.

**Comment by veillette** [comment]
Thanks @jessegreenberg.  
Since this is clearly unrelated to the conversion from PropertySet to Property, i'll go ahead and addressed #84.

**Comment by jessegreenberg** [comment]
Great thanks @veillette.  The layout should be fixed in the above commit.  Is there anything else to do for this issue?

**Comment by veillette** [comment]
I've reviewed your commits. Everything looks good. Closing.
