### ISSUE TITLE
Should these strings be internationalized?

### ISSUE THREAD

**Issue by samreid** [phetsims/trig-tour#88]
In https://github.com/phetsims/scenery-phet/issues/353 @jessegreenberg said:

> I reviewed sims assigned to me through responsible_dev.md. The only one that uses math symbols is trig-tour, but they symbols have been added to translatable strings so I can't use MathSymbols.js there.

These internationalized strings are in Trig Tour:

```json
  "infinitySymbol": {
    "value": "\u221E"
  },
  "pi": {
    "value": "\u03c0"
  },
  "plusMinus": {
    "value": "\u00B1"
  },
  "theta": {
    "value": "\u03b8"
  },
```

We normally do not internationalize mathematical symbols--is there a reason they were internationalized for this sim?

It is difficult to rename translated strings, but easy to remove them, so if it's better to un-internationalize them we can do that.

**Comment by jessegreenberg** [comment]
Hmm, I remember some discussion about this. Ill peruse the issues.

**Comment by jessegreenberg** [comment]
From https://github.com/phetsims/trig-tour/issues/16, @ariel-phet said

> We should allow theta to be translatable, it does no harm to allow translators that freedom does it?
...
We give translators the freedom to do whatever they wish in general, we tend to leave it up to them to make these sort of judgement calls. And yes, x and y should be translatable IMO
...
Usually the only things we don't allow to be translated are more on the legal side, such as our names in the credits or our copyright statement or such.

That conversation is several years old now, I think we have changed our thoughts about this. I am happy to use MathSymbols.js instead but maybe we should check some translations to see if anyone is leveraging the ability to translate these.

**Comment by jessegreenberg** [comment]
I searched through babel - none of the translators modified these strings. I am OK replacing with MathSymbols.js.

**Comment by jessegreenberg** [comment]
Done in the above commits. Closing.

**Comment by amanda-phet** [comment]
>That conversation is several years old now, I think we have changed our thoughts about this.

That's correct. We typically do NOT allow x and y to be translated anymore. Thanks for investigating and making this update!
