### ISSUE TITLE
May want to set limit on number of rotations

### ISSUE THREAD

**Issue by bryo5363** [phetsims/trig-tour#9]
I successfully filled the screen with trace lines from rotations. Maybe a limit should be set on the amount of rotations so the screen does not get cluttered

![screen shot 2015-07-27 at 12 53 36 pm](https://cloud.githubusercontent.com/assets/7717368/8914797/88e11322-345e-11e5-9498-f9895b9eecbc.png)

**Comment by elisemorgan** [comment]
I agree with @bryo5363 because the sim freezes a lot (on the iPad 2 iOS8) when there are a lot of rotations on the screen.

**Comment by amanda-phet** [comment]
We knew you'd probably try to do that! We also figured that most students in a classroom would get bored after a while... 

@elisemorgan you say the sim freezes on the iPad after a lot of rotations- how many rotations are "a lot"?

**Comment by elisemorgan** [comment]
![image](https://cloud.githubusercontent.com/assets/12610678/8917968/879bc4da-3472-11e5-99a0-6b3def624ba2.jpg)
@amanda-phet

**Comment by amanda-phet** [comment]
We either need to make it so that we can do an infinite number of rotations without compromising performance or set a limit.

**Comment by ariel-phet** [comment]
@dubson lets also layer the "graph view" above the drawing of the rotations (the panels look really nice layered above the rotations)

**Comment by jessegreenberg** [comment]
The number of rotations was limited to +/- 25.25 so that the spiral indicator is limited to the unit circle panel.  This behavior was discussed with @amanda-phet and @dubson as part of issue #36.
![spiral_limit](https://cloud.githubusercontent.com/assets/6396244/10493282/81690b16-726d-11e5-9b38-da9286911e84.PNG)

Closing.
