### ISSUE TITLE
Change casing for "Special angles" 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/trig-tour#90]
In this sim "Special angles" should be changed to "Special Angles" as we typically use title case for checkboxes and radio buttons

![45118216-23ed8b80-b115-11e8-8562-5c056f664ed2](https://user-images.githubusercontent.com/4051174/45127923-2b725c00-b138-11e8-9d3b-c02ebc4ed4e7.png)

**Comment by phet-steele** [comment]
@ariel-phet done in https://github.com/phetsims/trig-tour/commit/5c587c9cc433f14f826a7cdabc40ee1d20656ca1 and https://github.com/phetsims/trig-tour/commit/e7223a8dc80dd62c6b02b8f714d6ef53278cd0f0.

**Comment by kathy-phet** [comment]
This is in the published version, so must have been deployed. Closing
