### ISSUE TITLE
CT: Unloaded frame before complete

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/trig-tour#91]
```
trig-tour : fuzz : require.js-canvas : load
Unloaded frame before complete, window.location probably changed
id: Bayes Chrome
Approximately 11/6/2018, 10:41:12 PM
trig-tour : fuzz : require.js-canvas : run
Unloaded frame before complete, window.location probably changed
id: Bayes Chrome
Approximately 11/6/2018, 10:41:12 PM
```

**Comment by jessegreenberg** [comment]
Thanks for making an issue @KatieWoe. This specific error comes up on CT from time to time and is very unlikely to be a sim specific problem. @KatieWoe is there a good place where we can document issues like this?

**Comment by KatieWoe** [comment]
Maybe the QA book?  I'm not sure.

**Comment by phet-steele** [comment]
@KatieWoe please refer to this line in the QA book:

>If a simulation does not load in 40 seconds, then an error is given. If a window location changes, then an error is given. If this occurs frequently, then notify a developer.

If this error is not happening frequently, there is no need to log anything.

**Comment by KatieWoe** [comment]
Ok.  Thanks.

**Comment by phet-steele** [comment]
I should say: "there is no need to log anything [or make an issue]".
