### ISSUE TITLE
replace StringUtils.format

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/trig-tour#92]
Noted in https://github.com/phetsims/scenery-phet/issues/446#issuecomment-460732512...

In CoordinatesRow:

```js
var XYEqualsPattern = '(' + '{0}' + ',' + '{1}' + ')' + equalString;
var XYEqualString = StringUtils.format( XYEqualsPattern, xString, yString );
```

First, let's do something about those var names. Var names start with lowercase, not uppercase.

Second is the use of a string pattern.  If you're using `StringUtils.format` to avoid string concatenation, why use string concat to create the pattern? And why tack on `equalString` using string concat?   I would expect to see:

```js
var xyEqualString = StringUtils.format( '({0},{1}){2}', xString, yString, equalString );
```

Since this doesn't involve any translated strings, it should technically be converted to named placeholders and `StringUtils.fillIn`, i.e.:

```js
var xyEqualString = StringUtils.fillIn( '({{x}},{{y}}{{equal}}', {
  x: xString,
  y: yString,
  equal: equalString
} );
```

But... I see little value in using a string pattern here, and I think string concat would be fine, probably even clearer.  I.e.:

```js
var xyEqualString = '(' + xString + ',' + yString + ')' + equalString;
```

**Comment by pixelzoom** [comment]
This would also be an excellent place to use an ES6 template string. Note the use of backquotes:

```js
var xyEqualString = `(${xString},${yString})${equalString}`;
```

**Comment by jessegreenberg** [comment]
Thanks, changed to an ES6 template string in the above commit and removed and removed StringUtils.format here.
