### ISSUE TITLE
Consider using PropertyFractionNode (common)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/trig-tour#95]
Any sim that uses a fraction in a display might want to consider using (and modifying, if needed) the new fraction common code that was added due to https://github.com/phetsims/fractions-intro/issues/7 .

**Comment by jessegreenberg** [comment]
This is not a good candidate for PropertyFractionNode or its superclass unfortunately. The fractions in this sim have numerators/denominators with custom shapes for the minus sign and square root symbol. PropertyFractionNode is set up to work only with numbers - not even strings.

Ill go ahead and close this.
